[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Sujit Debnath", email = "sujit.debnath.bd@gmail.com"},
]
dependencies = []
requires-python = ">=3.8, <=3.9"
license = {text = "MIT"}
