[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Sujit Debnath", email = "sujit.debnath.bd@gmail.com"},
]
dependencies = [
    "pandas>=2.0.1",
]
requires-python = ">=3.8, <=3.9"
license = {text = "MIT"}
