name: Continuous Integration Pipeline

on:
  push:
    paths:
      - '**'
      - '!exercise/**'
  pull_request:
    branches:
      - main

jobs:
  build-and-tests-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Install dependencies
        run: |
          pip install --user pdm
          pdm install

      - name: Run tests
        run: |
          cd project
          chmod +x tests.sh
          sh tests.sh

      - name: Send Slack notification on test failure
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST \
          -H 'Content-type: application/json' \
          --data '{
              "blocks": [
                  {
                      "type": "header",
                      "text": {
                          "type": "plain_text",
                          "text": "Test result of repo ${{ github.repository }}"
                      }
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "Test failed!\nPlease check at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                      }
                  }
              ]
          }' $SLACK_WEBHOOK_URL
