name: CI pipeline for running tests

on:
  push:
    paths-ignore:
      - 'exercise/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --user pdm
          pdm install

      - name: Run tests
        run: |
          cd project
          chmod +x tests.sh
          sh tests.sh
